---
name: "orchestrator-ci"

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  issues: write

jobs:
  orchestrator-ci:
    uses: "urukube/orchestrator-plane-setup/.github/workflows/main.yml@v1"
    with:
      tfvar_file_path: "orchestrator.tfvars"
      bucket_name: "orchestrator-bucket"
      approvers: "dilipsamanta"
      master_s3_directory: "orchestrator"
      module_ref: "v1"
    secrets: inherit
